language: cpp
dist: bionic
os: linux

compiler:
  - gcc
  - clang

env:
  global:
    - CACHE_DIR=~/cached-deps
    - YCM_CHECKOUT=ycm-0.11
  jobs:
    - YARP_CHECKOUT=yarp-3.4
    - YARP_CHECKOUT=yarp-3.3

jobs:
  include:
    - if: type = cron
      compiler: gcc
      env: ROBOTOLOGY_CHECKOUT=master
    - if: type = cron
      compiler: clang
      env: ROBOTOLOGY_CHECKOUT=master

cache:
  directories: $CACHE_DIR

addons:
  apt:
    packages:
    - libopencv-dev
    - libpcl-dev
    - libproj-dev # needed by libpcl-dev on Xenial (known bug)

before_install:
  #-- Code coverage
  - if [ "$CXX" = "g++" ]; then gem install coveralls-lcov; fi

install:
  #-- Install YCM
  - >
    source "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name YCM
    --repo-url https://github.com/robotology/ycm
    --repo-checkout "${ROBOTOLOGY_CHECKOUT:-$YCM_CHECKOUT}"

  #-- Install YARP
  - >
    source "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name YARP
    --repo-url https://github.com/robotology/yarp
    --repo-checkout "${ROBOTOLOGY_CHECKOUT:-$YARP_CHECKOUT}"
    --additional-cmake-options "-DSKIP_ACE:BOOL=ON"
    --prepend-to-linker-path lib
    --additional-export-paths "YARP_DATA_DIRS;share/yarp"

  #-- Install color-debug
  - >
    source "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name COLOR_DEBUG
    --repo-url https://github.com/roboticslab-uc3m/color-debug
    --repo-checkout master

before_script:
  - mkdir -p "$TRAVIS_BUILD_DIR/build" && cd "$_"
  - cmake .. -DCMAKE_INSTALL_PREFIX="$PWD/install" -DENABLE_coverage:BOOL=ON
  - make install
  - export LD_LIBRARY_PATH=$PWD/install/lib:$LD_LIBRARY_PATH
  - export YARP_DATA_DIRS=$PWD/install/share/roboticslab-vision:$YARP_DATA_DIRS

script:
  - echo "No unit tests available"

after_success:
  #-- Code coverage
  - if [ "$CXX" = "g++" ]; then source "$TRAVIS_BUILD_DIR/scripts/travis/coverage.sh"; fi

  - make uninstall
